---
stages:
- name: Globalize
  inputs:
  - type: git
    branch: master
  triggers:
  - type: stage
  jobs:
  - name: machine translation
    type: builder
    extension_id: ibm.devops.services.pipeline.globalization.builder
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
    SETUP_SERVICE_SPACE: 'true'
    INPUT_PATTERN: translation_en.properties
- name: Package application
  inputs:
  - type: job
    stage: Globalize
    job: machine translation
  triggers:
  - type: stage
  jobs:
  - name: maven
    type: builder
    artifact_dir: target
    build_type: maven
    script: |-
      #!/bin/bash
      # build the application 
      mvn -B package
      #copy deploy utility
      cp setup_services.py ${ARCHIVE_DIR}
- name: Deploy
  inputs:
  - type: job
    stage: Package application
    job: maven
  properties:
  - name: NY_TIMES_API_KEY
    value: 40c11f9c846004aff534eaf95526988c:11:72351455
    type: secure
  - name: DREAM_BOOKS_API_KEY
    value: 33b011bc2741dca46f0e59d4ef6d3571bce4f569
    type: secure
  - name: ALCHEMY_API_KEY
    value: 6ee0287255ef84d6096e16a72bae869bcebee69c
    type: secure
  jobs:
  - name: Deploy
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash
      set +x 
      export red='\e[0;31m'
      export no_color='\e[0m' # No Color
      if [ -z "${NY_TIMES_API_KEY}" ]; then 
          echo -e "${red}Please set NY_TIMES_API_KEY in stage environment properties.  This can be obtained from http://developer.nytimes.com ${no_color}"
          exit 1
      fi 
      if [ -z "${DREAM_BOOKS_API_KEY}" ]; then 
          echo -e "${red}Please set DREAM_BOOKS_API_KEY in stage environment properties.  This can be obtained from http://idreambooks.com/api ${no_color}"
          exit 1
      fi 
      if [ -z "${ALCHEMY_API_KEY}" ]; then 
          echo -e "${red}Please set ALCHEMY_API_KEY in stage environment properties.  This can be obtained from http://www.alchemyapi.com ${no_color}"
          exit 1
      fi 
      cf push "${CF_APP}" -p BookClub-1.0-SNAPSHOT.war -m 768M --no-start
      python setup_services.py --app ${CF_APP}
      cf set-env "${CF_APP}" NY_TIMES_URL api.nytimes.com
      cf set-env "${CF_APP}" NY_TIMES_API_KEY ${NY_TIMES_API_KEY}
      cf set-env "${CF_APP}" DREAM_BOOKS_URL idreambooks.com
      cf set-env "${CF_APP}" DREAM_BOOKS_API_KEY ${DREAM_BOOKS_API_KEY}
      cf set-env "${CF_APP}" ALCHEMY_API_KEY ${ALCHEMY_API_KEY}
      cf start "${CF_APP}"


      # view logs
      #cf logs "${CF_APP}" --recent
